### ISSUE TITLE
It broke gcc on Linux

### ISSUE THREAD

**Issue by 183amir** [conda-forge/isl-feedstock#1] opened 2016-04-20 08:05 UTC
```
Removing old build environment
Removing old work directory
BUILD START: bob.learn.em-2.0.8-py27_0
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ..........
Solving package specifications: .........

The following NEW packages will be INSTALLED:

    bob.blitz:            2.0.8-np111py27_4
    bob.core:             2.1.2-py27_1     
    bob.extension:        2.0.11-py27_4    
    bob.io.base:          2.0.8-py27_0     
    bob.learn.activation: 2.0.4-py27_2     
    bob.learn.linear:     2.0.7-py27_2     
    bob.math:             2.0.3-py27_2     
    bob.sp:               2.0.4-py27_2     
    boost:                1.60.0-py27_0    
    cloog:                0.18.0-0         
    cmake:                3.5.0-3          
    gcc:                  4.8.5-3          
    gmp:                  6.1.0-2          
    hdf5:                 1.8.16-2         
    icu:                  56.1-2           
    isl:                  0.16.1-0         
    libblitz:             0.10-1           
    libgcc:               4.8.5-1          
    libgfortran:          3.0-0            
    mkl:                  11.3.1-0         
    mpc:                  1.0.3-1          
    mpfr:                 3.1.4-1          
    numpy:                1.11.0-py27_0    
    openblas:             0.2.14-4         
    openssl:              1.0.2g-0         
    pip:                  8.1.1-py27_1     
    pkg-config:           0.28-1           
    python:               2.7.11-0         
    readline:             6.2-2            
    setuptools:           20.7.0-py27_0    
    sqlite:               3.9.2-0          
    tk:                   8.5.18-0         
    wheel:                0.29.0-py27_0    
    zlib:                 1.2.8-0          

Linking packages ...
/home/amir/miniconda/envs/_build/gcc/libexec/gcc/x86_64-unknown-linux-gnu/4.8.5/cc1: error while loading shared libraries: libisl.so.10: cannot open shared object file: No such file or directory           |  76%
Installation failed: gcc is not able to compile a simple 'Hello, World' program.
Error: post-link failed for: gcc-4.8.5-3
```

**Comment by pelson** [comment] 2016-04-20 09:40
Closing as there is nothing wrong with isl - the problem is with the GCC that is provided by defaults. Discussion taking place at https://github.com/conda-forge/staged-recipes/issues/436.

Thanks @183amir!

**Closed as completed by pelson** 2016-04-20 09:40 UTC
